name: Deploy MyFin (Private Tailscale CI/CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Actualizar Repositorio y Reconstruir Docker
        run: |
          cd ~/MyFin
          git pull origin main
          docker compose up -d --build